### PR TITLE
🤌 CB colors to CueDS

### PR DESCRIPTION
**Pull request by thaoms**
This PR will implement that CueDS color scheme for our react components, based on the feedback here we can can focus on the engagor PR

Related to CB-24974

### CODE REVIEW

**Review by cedricengagor — APPROVED** [review]
It's very hard to distinct between a warning button and an error button, but if those were defined by Qualtrics I'm okay with it I guess 😂

**Review by cedricengagor — CHANGES_REQUESTED** [review]
Transparent buttons are broken, I see that some important statements were removed. Probably broke it because of that.

**Comment by thaoms** [comment]
> It's very hard to distinct between a warning button and an error button, but if those were defined by Qualtrics I'm okay with it I guess 😂

I don't agree with this one. It's just orange and red? Yes it is approved by Qualtrics, and if you don't see the difference I would get my eyes checked. :D

**Review by cedricengagor — APPROVED** [review]

**Review by matthias-deschoenmacker — APPROVED** [review]
I agree with Cedric tbh, I see the difference but I can see people with light colorblindness not seeing the difference. Then again Qualtrics decides so good job Thomas! 😁

**Pull request merged**
